### ISSUE TITLE
[IMPORTANT SHIT] Make the actual code

### ISSUE THREAD

**Issue by malmeloo** [Teapot-Tools/teapot-tools-java#1]
This has been dead for several months and I honestly almost forgot this still existed but this is still a very important thing and needs fixing immediately

**Comment by Artuto** [comment]
Petition to rename this to "Make the actual code"

**Comment by Artuto** [comment]
Petition accepted.

**Comment by Artuto** [comment]
Well that is disappointing

**Comment by malmeloo** [comment]
We understand your disappointment, however there is simply not enough demand for this feature to justify its implementation. Given the limited capacity of our team, we sometimes have to make decisions like this in order to keep our main focus on the spirit of the product. Since demand for this feature appears to be limited even after almost 6 years, we found that this decision was necessary in order to keep the development momentum we have now.

Thank you for your understanding.
